name: Horse
version: 0.2
description: Play Horse in Minecraft
author: Fernando Barillas @fbis251
main: com.fernandobarillas.mchorse.McHorse
commands:
  horse:
    description: Starts horse session
    usage: /<command> [add, remove, start, stop, score, players] [player]
    permission: mchorse.add
    permission-message: You don't have permission to add player <permission>
  h:
    description: Shortcut for /horse
    usage: /<command>

permissions:
    mchorse.*:
        description: Gives access to all MCHorse commands
        children:
            mchorse.add: true
            mchorse.remove: true
            mchorse.start: true
            mchorse.end: true
    mchorse.add:
        description: Allows players to add themselves to the horse queue
        default: true
    mchorse.remove:
        description: Allows players to remove themselves from the horse queue
        default: true
    mchorse.start:
        description: Allows starting a new game of horse
        default: op
    mchorse.end:
        description: Allows ending a game of horse
        default: op
